version: "3"

services:
  backend:
    build:
      context: ./backend/
    ports:
      - 8000:8000
    volumes:
      - ./log:/log
      - ./backend/config:/config
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx/
    volumes:
      - ./log:/log
      - ./frontend/build:/frontend
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - backend
