// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	entity "backend/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockMediaRepository is an autogenerated mock type for the MediaRepository type
type MockMediaRepository struct {
	mock.Mock
}

type MockMediaRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaRepository) EXPECT() *MockMediaRepository_Expecter {
	return &MockMediaRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *MockMediaRepository) Create(_a0 *entity.Media) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Media) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMediaRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *entity.Media
func (_e *MockMediaRepository_Expecter) Create(_a0 interface{}) *MockMediaRepository_Create_Call {
	return &MockMediaRepository_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *MockMediaRepository_Create_Call) Run(run func(_a0 *entity.Media)) *MockMediaRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Media))
	})
	return _c
}

func (_c *MockMediaRepository_Create_Call) Return(_a0 error) *MockMediaRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_Create_Call) RunAndReturn(run func(*entity.Media) error) *MockMediaRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockMediaRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMediaRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockMediaRepository_Expecter) Delete(id interface{}) *MockMediaRepository_Delete_Call {
	return &MockMediaRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockMediaRepository_Delete_Call) Run(run func(id uint)) *MockMediaRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockMediaRepository_Delete_Call) Return(_a0 error) *MockMediaRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_Delete_Call) RunAndReturn(run func(uint) error) *MockMediaRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *MockMediaRepository) Get(id uint) (*entity.Media, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Media
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entity.Media, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *entity.Media); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Media)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMediaRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id uint
func (_e *MockMediaRepository_Expecter) Get(id interface{}) *MockMediaRepository_Get_Call {
	return &MockMediaRepository_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockMediaRepository_Get_Call) Run(run func(id uint)) *MockMediaRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockMediaRepository_Get_Call) Return(_a0 *entity.Media, _a1 error) *MockMediaRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_Get_Call) RunAndReturn(run func(uint) (*entity.Media, error)) *MockMediaRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with given fields: id
func (_m *MockMediaRepository) Load(id uint) (*entity.MediaView, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *entity.MediaView
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entity.MediaView, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *entity.MediaView); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.MediaView)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockMediaRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - id uint
func (_e *MockMediaRepository_Expecter) Load(id interface{}) *MockMediaRepository_Load_Call {
	return &MockMediaRepository_Load_Call{Call: _e.mock.On("Load", id)}
}

func (_c *MockMediaRepository_Load_Call) Run(run func(id uint)) *MockMediaRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockMediaRepository_Load_Call) Return(_a0 *entity.MediaView, _a1 error) *MockMediaRepository_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_Load_Call) RunAndReturn(run func(uint) (*entity.MediaView, error)) *MockMediaRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: _a0
func (_m *MockMediaRepository) Search(_a0 *entity.Filter) (*[]entity.MediaResult, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *[]entity.MediaResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.Filter) (*[]entity.MediaResult, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.Filter) *[]entity.MediaResult); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.MediaResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.Filter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockMediaRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - _a0 *entity.Filter
func (_e *MockMediaRepository_Expecter) Search(_a0 interface{}) *MockMediaRepository_Search_Call {
	return &MockMediaRepository_Search_Call{Call: _e.mock.On("Search", _a0)}
}

func (_c *MockMediaRepository_Search_Call) Run(run func(_a0 *entity.Filter)) *MockMediaRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Filter))
	})
	return _c
}

func (_c *MockMediaRepository_Search_Call) Return(_a0 *[]entity.MediaResult, _a1 error) *MockMediaRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaRepository_Search_Call) RunAndReturn(run func(*entity.Filter) (*[]entity.MediaResult, error)) *MockMediaRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *MockMediaRepository) Update(_a0 *entity.Media) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Media) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMediaRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 *entity.Media
func (_e *MockMediaRepository_Expecter) Update(_a0 interface{}) *MockMediaRepository_Update_Call {
	return &MockMediaRepository_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *MockMediaRepository_Update_Call) Run(run func(_a0 *entity.Media)) *MockMediaRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Media))
	})
	return _c
}

func (_c *MockMediaRepository_Update_Call) Return(_a0 error) *MockMediaRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaRepository_Update_Call) RunAndReturn(run func(*entity.Media) error) *MockMediaRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaRepository creates a new instance of MockMediaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaRepository {
	mock := &MockMediaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
